export const mockMessages = [
    {
        id: "msg1",
        sender: {
            name: "Alex Johnson",
            email: "alex@example.com",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        subject: "Project Update - Q1 Goals",
        preview: "I wanted to share some updates on our Q1 goals and progress so far...",
        content:
            "I wanted to share some updates on our Q1 goals and progress so far. We've made significant strides in the last few weeks, and I'm pleased to report that we're on track to meet our targets.",
        fullContent: [
            "I wanted to share some updates on our Q1 goals and progress so far. We've made significant strides in the last few weeks, and I'm pleased to report that we're on track to meet our targets.",
            "The development team has completed the core functionality for the new feature set, and QA is now testing everything. We should be able to roll out the update to customers by the end of the month.",
            "Let me know if you have any questions or concerns about the timeline.",
            "Best regards,",
            "Alex",
        ],
        timestamp: "10:30 AM",
        read: false,
        priority: true,
        spam: false,
    },
    {
        id: "msg2",
        sender: {
            name: "Marketing Team",
            email: "marketing@example.com",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        subject: "New Campaign Launch",
        preview: "We're excited to announce our new marketing campaign launching next week...",
        timestamp: "Yesterday",
        read: true,
        priority: false,
        spam: false,
    },
    {
        id: "msg3",
        sender: {
            name: "Sarah Williams",
            email: "sarah@example.com",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        subject: "Meeting Rescheduled",
        preview: "Due to a conflict, we need to reschedule our meeting to Thursday at 2 PM...",
        timestamp: "Yesterday",
        read: true,
        priority: true,
        spam: false,
    },
    {
        id: "msg4",
        sender: {
            name: "Unknown Sender",
            email: "win@prizes-now.com",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        subject: "YOU'VE WON $1,000,000!!!",
        preview: "Click here to claim your prize immediately before it expires...",
        timestamp: "2 days ago",
        read: false,
        priority: false,
        spam: true,
    },
    {
        id: "msg5",
        sender: {
            name: "David Chen",
            email: "david@example.com",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        subject: "Feedback on your proposal",
        preview: "I've reviewed your proposal and have some thoughts to share...",
        timestamp: "2 days ago",
        read: true,
        priority: false,
        spam: false,
    },
    {
        id: "msg6",
        sender: {
            name: "HR Department",
            email: "hr@example.com",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        subject: "Important: Benefits Update",
        preview: "Please review the changes to our benefits package effective next month...",
        timestamp: "3 days ago",
        read: false,
        priority: true,
        spam: false,
    },
    {
        id: "msg7",
        sender: {
            name: "Pharmacy Discount",
            email: "meds@cheap-rx-now.net",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        subject: "Discount Medications - 90% OFF TODAY ONLY",
        preview: "Buy medications online at incredible discounts. No prescription needed...",
        timestamp: "4 days ago",
        read: false,
        priority: false,
        spam: true,
    },
    {
        id: "msg8",
        sender: {
            name: "Michael Rodriguez",
            email: "michael@example.com",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        subject: "Question about the API documentation",
        preview: "I was looking through the API docs and noticed something that might need clarification...",
        timestamp: "5 days ago",
        read: true,
        priority: false,
        spam: false,
    },
    {
        id: "msg9",
        sender: {
            name: "Emma Davis",
            email: "emma@example.com",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        subject: "Team lunch next Friday",
        preview: "I'd like to organize a team lunch next Friday to celebrate our recent launch...",
        timestamp: "1 week ago",
        read: true,
        priority: false,
        spam: false,
    },
    {
        id: "msg10",
        sender: {
            name: "System Administrator",
            email: "admin@example.com",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        subject: "System Maintenance Notice",
        preview: "The system will be down for maintenance this Saturday from 2 AM to 4 AM...",
        timestamp: "1 week ago",
        read: true,
        priority: true,
        spam: false,
    },
    {
        id: "msg11",
        sender: {
            name: "Bank Alert",
            email: "security@bank-verify-now.com",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        subject: "URGENT: Verify Your Account Information",
        preview: "Your account has been limited. Click here to verify your information immediately...",
        timestamp: "1 week ago",
        read: false,
        priority: false,
        spam: true,
    },
]

